@url = http://localhost:3000/pantheons
GET {{url}}
  
###
POST {{url}}
Content-Type: application/json

{
    "id_pantheon" : 4,
    "name_pantheon": "Celta",
    "lore_pantheon": "es el panteon de morrigan"
}