@url = http://localhost:3000/pantheons
GET {{url}}
  
###
POST {{url}}
Content-Type: application/json

{
    "id_pantheon" : 5,
    "name_pantheon": "Romano",
    "lore_pantheon": "Este es el panteon de bellona"
}